### ISSUE TITLE
Implement multi-processing

### ISSUE THREAD

**Issue by sxppro** [Monash-Connected-Autonomous-Vehicle/AV-Competition-Software#11]
Python is very slow and capturing an image from the Pi camera requires (~200ms according to Yide) so we will need some multiprocessing to avoid vehicles jerking, since the drive controls are done through Python as well

Look into multiprocessing package: https://docs.python.org/3/library/multiprocessing.html

**Comment by dylan-gonzalez** [comment]
might be good to take a look at the picamera package if you haven't already https://forums.raspberrypi.com/viewtopic.php?t=342921

**Comment by sxppro** [comment]
yide is using picamera2 alr but yea i needa look at the docs

**Comment by sxppro** [comment]
Was not needed in the end :)
