### ISSUE TITLE
Test hardware drive interface through software

### ISSUE THREAD

**Issue by sxppro** [Monash-Connected-Autonomous-Vehicle/AV-Competition-Software#7]
We need to test whether the driving-related methods are working, as they will be used for controlling the vehicle to stop at traffic lights and lane following.

These methods are found in the [`driving_tools.py`](https://github.com/Monash-Connected-Autonomous-Vehicle/AV-Competition-Software/blob/main/mcav_av_workshop/driving_tools.py)

**Comment by dylan-gonzalez** [comment]
should this be moved into In Progress?
It's ready to test right? @sxppro

**Comment by sxppro** [comment]
@dylan-gonzalez mhm yeap i'll update it

**Comment by sxppro** [comment]
Done thanks to Yide :D
