### ISSUE TITLE
Test image detection and colour highlight on the physical vehicles

### ISSUE THREAD

**Issue by dylan-gonzalez** [Monash-Connected-Autonomous-Vehicle/AV-Competition-Software#8]
There are several components to this:

- [x] Get an image feed from the Pi camera
- [x] Display the live image feed (if possible)
- [x] Test run our image detection and colour highlight logic on the feed

**Comment by sxppro** [comment]
On hold cause we wanna use OpenCV object detection here: https://github.com/orgs/Monash-Connected-Autonomous-Vehicle/projects/8/views/14?pane=issue&itemId=43290287
