### ISSUE TITLE
Setup code upload workflow to Pi's

### ISSUE THREAD

**Issue by dylan-gonzalez** [Monash-Connected-Autonomous-Vehicle/AV-Competition-Software#9]
We need a workflow so that students can upload their edited code onto the Pi's.

Jai mentioned there is a basically SMB-like file sharing system that can be used so that laptops provided by us can directly edit on the Pi's

**Comment by sxppro** [comment]
something called Samba

**Comment by sxppro** [comment]
Not needed cause we SSH'd and VNC'd instead 😄
